import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F1729',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 100, // Đảm bảo có thể scroll xem hết nội dung, tránh bị che bởi navigation bar
  },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 12,
  },
  timeText: {
    fontSize: 11.1,
    lineHeight: 16,
    color: '#FFFFFF',
    fontFamily: 'Inter',
  },
  statusBarIcons: {
    flexDirection: 'row',
    gap: 8,
  },
  statusIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusIconGradient: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusIconDark: {
    backgroundColor: '#1A2332',
  },
  notificationDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FB2C36',
    top: 4,
    right: 4,
  },
  userSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatarContainer: {
    marginRight: 12,
  },
  avatarBorder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#00D492',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarGradient: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '400',
  },
  userInfo: {
    flex: 1,
  },
  greetingText: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#99A1AF',
    marginBottom: 4,
  },
  userNameText: {
    fontSize: 14.3,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  balanceSection: {
    marginBottom: 24,
  },
  balanceLabel: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#99A1AF',
    marginBottom: 8,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  balanceAmount: {
    fontSize: 27.4,
    lineHeight: 36,
    color: '#FFFFFF',
    marginRight: 8,
  },
  eyeButton: {
    padding: 4,
  },
  card: {
    marginBottom: 20,
    borderRadius: 14,
    overflow: 'hidden',
  },
  aiCardGradient: {
    padding: 20,
    minHeight: 164,
  },
  aiCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  aiIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  aiHeaderText: {
    flex: 1,
  },
  aiTitle: {
    fontSize: 14.6,
    lineHeight: 24,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  aiSubtitle: {
    fontSize: 11.4,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  aiInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aiInputButton: {
    width: 40,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  aiSendButton: {
    opacity: 0.5,
  },
  aiInput: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 16,
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 16,
  },
  suggestionsCardGradient: {
    padding: 20,
    minHeight: 604,
  },
  suggestionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  suggestionsIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  suggestionsHeaderText: {
    flex: 1,
  },
  suggestionsTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  suggestionsDate: {
    fontSize: 11.6,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  goalBox: {
    backgroundColor: 'rgba(253, 199, 0, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(253, 199, 0, 0.3)',
    borderRadius: 14,
    padding: 13,
    marginBottom: 20,
  },
  goalHeader: {
    marginBottom: 12,
  },
  goalText: {
    fontSize: 11.4,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  goalStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  goalStatBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    padding: 8,
  },
  goalStatLabel: {
    fontSize: 9.4,
    lineHeight: 15,
    color: 'rgba(255, 255, 255, 0.6)',
    marginBottom: 4,
  },
  goalStatValue: {
    fontSize: 13.5,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  goalDescription: {
    fontSize: 13.3,
    lineHeight: 20,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  statBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    padding: 8,
    alignItems: 'center',
    minHeight: 84,
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 9.5,
    lineHeight: 15,
    color: 'rgba(255, 255, 255, 0.6)',
    marginTop: 4,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 12.1,
    lineHeight: 20,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  tipsSection: {
    marginTop: 20,
  },
  tipsTitle: {
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 8,
  },
  tipBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
  },
  tipBullet: {
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.6)',
    marginRight: 8,
  },
  tipText: {
    flex: 1,
    fontSize: 11.3,
    lineHeight: 16,
    color: '#FFFFFF',
  },
  darkCard: {
    backgroundColor: '#1A2332',
    padding: 20,
  },
  overviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  overviewTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  overviewActions: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  overviewButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#0F1729',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overviewDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F1729',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 4,
  },
  overviewDropdownText: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  summaryStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  summaryStat: {
    flex: 1,
  },
  summaryLabel: {
    fontSize: 10.9,
    lineHeight: 16,
    color: '#99A1AF',
    marginBottom: 8,
  },
  summaryValue: {
    fontSize: 14.5,
    lineHeight: 24,
  },
  incomeValue: {
    color: '#05DF72',
  },
  expenseValue: {
    color: '#FF6467',
  },
  differenceValue: {
    color: '#FFFFFF',
  },
  chartContainer: {
    height: 96,
    marginBottom: 20,
  },
  barChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '100%',
    paddingHorizontal: 20,
  },
  bar: {
    width: 90,
    borderRadius: 6,
  },
  incomeBar: {
    backgroundColor: '#10B981',
  },
  expenseBar: {
    backgroundColor: '#EF4444',
  },
  pieChartSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  pieChartPlaceholder: {
    width: 140,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pieChartCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#2A2A3E',
  },
  legend: {
    flex: 1,
    marginLeft: 16,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  legendName: {
    flex: 1,
    fontSize: 10.9,
    lineHeight: 16,
    color: '#D1D5DC',
  },
  legendPercentage: {
    fontSize: 10.9,
    lineHeight: 16,
    color: '#99A1AF',
  },
  historyButton: {
    borderWidth: 1,
    borderColor: '#4A5565',
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  historyButtonText: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#D1D5DC',
  },
  limitHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  limitTitle: {
    fontSize: 15,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  limitActions: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  limitButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#1A2332',
    justifyContent: 'center',
    alignItems: 'center',
  },
  limitLink: {
    fontSize: 13,
    lineHeight: 20,
    color: '#51A2FF',
  },
  limitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  limitIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  limitEmoji: {
    fontSize: 20,
    lineHeight: 28,
  },
  limitInfo: {
    flex: 1,
  },
  limitLabel: {
    fontSize: 15.4,
    lineHeight: 24,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  limitDate: {
    fontSize: 11.8,
    lineHeight: 16,
    color: '#99A1AF',
    marginBottom: 8,
  },
  limitAmount: {
    fontSize: 14.5,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  progressContainer: {
    marginBottom: 16,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#0F1729',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  todayBox: {
    alignSelf: 'flex-end',
    backgroundColor: '#0F1729',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  todayText: {
    fontSize: 11.4,
    lineHeight: 16,
    color: '#99A1AF',
  },
  bottomSpacing: {
    height: 40,
  },
  // Account Screen Styles
  accountHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingTop: 12,
  },
  accountTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  accountHeaderIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  accountHeaderIcon: {
    padding: 4,
  },
  accountTabs: {
    flexDirection: 'row',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1e2939',
  },
  accountTab: {
    flex: 1,
    paddingBottom: 12,
    alignItems: 'center',
  },
  accountTabActive: {
    position: 'relative',
  },
  accountTabText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#99A1AF',
    fontWeight: '500',
  },
  accountTabTextActive: {
    color: '#51A2FF',
  },
  accountTabUnderline: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#51A2FF',
  },
  accountTotalBalance: {
    backgroundColor: '#1A2332',
    borderRadius: 14,
    padding: 16,
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  accountTotalLabel: {
    fontSize: 14,
    lineHeight: 20,
    color: '#99A1AF',
  },
  accountTotalAmount: {
    fontSize: 18,
    lineHeight: 24,
    color: '#FF6900',
    fontWeight: '600',
  },
  accountCategoriesSection: {
    marginBottom: 20,
  },
  accountCategoriesLabel: {
    fontSize: 13,
    lineHeight: 20,
    color: '#99A1AF',
    marginBottom: 16,
  },
  accountCategory: {
    marginBottom: 16,
  },
  accountCategoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  accountCategoryName: {
    fontSize: 15,
    lineHeight: 22,
    color: '#00D492',
    fontWeight: '500',
  },
  accountItemsContainer: {
    marginTop: 8,
    gap: 12,
  },
  accountItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
  },
  accountItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  accountItemInfo: {
    flex: 1,
  },
  accountItemName: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    marginBottom: 4,
    fontWeight: '500',
  },
  accountItemAmount: {
    fontSize: 14,
    lineHeight: 20,
    color: '#99A1AF',
  },
  accountItemMenu: {
    padding: 4,
  },
  // Report Screen Styles
  reportHeader: {
    marginBottom: 20,
    paddingTop: 12,
  },
  reportHeaderTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  reportCurrentFinanceCard: {
    padding: 20,
    borderRadius: 14,
    minHeight: 180,
  },
  reportCurrentFinanceTitle: {
    fontSize: 13.2,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 12,
  },
  reportCurrentBalance: {
    fontSize: 32,
    lineHeight: 40,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 20,
  },
  reportFinanceBoxes: {
    flexDirection: 'row',
    gap: 12,
  },
  reportFinanceBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    padding: 16,
  },
  reportFinanceBoxContent: {
    flex: 1,
  },
  reportFinanceBoxLabel: {
    fontSize: 11.4,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    marginBottom: 4,
  },
  reportFinanceBoxValue: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  reportIncomeExpenseCard: {
    marginBottom: 20,
  },
  reportIncomeExpenseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  reportIncomeExpenseTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  reportIncomeExpenseSubtitle: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  reportViewDetailButton: {
    backgroundColor: '#51A2FF',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  reportViewDetailText: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  reportBarChartContainer: {
    height: 180,
    marginBottom: 20,
  },
  reportBarChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '100%',
    paddingHorizontal: 8,
  },
  reportBarChartMonth: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  reportBarChartBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    width: '100%',
    height: '85%',
    marginBottom: 8,
  },
  reportBar: {
    flex: 1,
    borderRadius: 4,
    minHeight: 4,
  },
  reportIncomeBar: {
    backgroundColor: '#10B981',
  },
  reportExpenseBar: {
    backgroundColor: '#EF4444',
  },
  reportBarChartMonthLabel: {
    fontSize: 10.9,
    lineHeight: 16,
    color: '#99A1AF',
    textAlign: 'center',
  },
  reportStatusMessage: {
    backgroundColor: '#0F1729',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  reportStatusMessageText: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
    textAlign: 'center',
  },
  reportFunctionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
    marginTop: 8,
  },
  reportFunctionCard: {
    width: '48%',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
  },
  reportFunctionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  reportFunctionLabel: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '500',
  },
  // Other Screen Styles
  otherHeader: {
    marginBottom: 20,
    paddingTop: 12,
  },
  otherTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  otherUserCard: {
    marginBottom: 20,
    borderRadius: 14,
    overflow: 'hidden',
  },
  otherUserCardGradient: {
    padding: 20,
    minHeight: 80,
    justifyContent: 'center',
  },
  otherUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  otherStatsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  otherStatCard: {
    flex: 1,
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 80,
  },
  otherStatValue: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
    marginBottom: 4,
  },
  otherStatLabel: {
    fontSize: 11.4,
    lineHeight: 16,
    color: '#99A1AF',
  },
  otherSection: {
    marginBottom: 24,
  },
  otherSectionTitle: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 12,
  },
  otherMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
  },
  otherMenuItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  otherMenuItemContent: {
    flex: 1,
  },
  otherMenuItemText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  otherMenuItemSubtext: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginTop: 2,
  },
  otherVersionContainer: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  otherVersionText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  otherLogoutButton: {
    borderWidth: 1,
    borderColor: '#FB2C36',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    marginBottom: 8,
  },
  otherLogoutButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  otherLogoutText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FB2C36',
    fontWeight: '500',
  },
  // Community Page Styles
  communityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 12,
  },
  communityBackButton: {
    padding: 4,
  },
  communityHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  communityTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  communitySubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  communityPostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#51A2FF',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 4,
  },
  communityPostButtonText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  communityFilterTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  communityFilterTab: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
    minHeight: 36,
  },
  communityFilterTabActive: {
    // Gradient will be applied via LinearGradient component
  },
  communityFilterTabGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 6,
  },
  communityFilterTabText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#99A1AF',
    fontWeight: '500',
  },
  communityFilterTabTextActive: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  communityStatsCard: {
    marginBottom: 20,
    borderRadius: 14,
    overflow: 'hidden',
  },
  communityStatsCardGradient: {
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  communityStatsCardLeft: {
    flex: 1,
  },
  communityStatsIcon: {
    marginBottom: 8,
  },
  communityStatsLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 4,
  },
  communityStatsValue: {
    fontSize: 28,
    lineHeight: 36,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  communityStatsCardRight: {
    alignItems: 'flex-end',
  },
  communityStatsToday: {
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
    marginBottom: 4,
  },
  communityStatsShared: {
    fontSize: 12,
    lineHeight: 18,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  communityPostCard: {
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  communityPostHeader: {
    marginBottom: 12,
  },
  communityPostUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  communityPostAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  communityPostAvatarText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  communityPostUserDetails: {
    flex: 1,
  },
  communityPostUserNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  communityPostUserName: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  communityPostCategoryTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  communityPostCategoryTagText: {
    fontSize: 10,
    lineHeight: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  communityPostTime: {
    fontSize: 11,
    lineHeight: 16,
    color: '#99A1AF',
  },
  communityPostContent: {
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
    marginBottom: 12,
  },
  communityPostActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  communityPostActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  communityPostActionText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  // Saving Goals Page Styles
  savingGoalsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 12,
  },
  savingGoalsBackButton: {
    padding: 4,
  },
  savingGoalsHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  savingGoalsHeaderIcon: {
    marginBottom: 8,
  },
  savingGoalsTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  savingGoalsSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  savingGoalsAddButton: {
    padding: 4,
  },
  savingGoalsSummaryStats: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  savingGoalsSummaryCard: {
    flex: 1,
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  savingGoalsSummaryLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginBottom: 8,
  },
  savingGoalsSummaryValue: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  savingGoalCard: {
    backgroundColor: '#1A2332',
    borderRadius: 14,
    padding: 20,
    marginBottom: 20,
  },
  savingGoalCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  savingGoalCardHeaderLeft: {
    flex: 1,
  },
  savingGoalCardTitle: {
    fontSize: 20,
    lineHeight: 28,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  savingGoalCardCategory: {
    fontSize: 13,
    lineHeight: 20,
    color: '#99A1AF',
  },
  savingGoalCardDelete: {
    padding: 4,
  },
  savingGoalProgressSection: {
    marginBottom: 20,
  },
  savingGoalProgressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  savingGoalProgressLabel: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  savingGoalProgressPercentage: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  savingGoalProgressBar: {
    marginBottom: 8,
  },
  savingGoalProgressBarTrack: {
    height: 8,
    backgroundColor: '#0F1729',
    borderRadius: 4,
    overflow: 'hidden',
  },
  savingGoalProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  savingGoalAmountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  savingGoalCurrentAmount: {
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  savingGoalTargetAmount: {
    fontSize: 14,
    lineHeight: 20,
    color: '#99A1AF',
  },
  savingGoalMetrics: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  savingGoalMetricCard: {
    flex: 1,
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  savingGoalMetricLabel: {
    fontSize: 11,
    lineHeight: 16,
    color: '#99A1AF',
    marginTop: 8,
    marginBottom: 4,
  },
  savingGoalMetricValue: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
  },
  savingGoalQuickAddButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  savingGoalQuickAddButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#0F1729',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingGoalQuickAddButtonGradient: {
    flex: 1,
    width: '100%',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingGoalQuickAddButtonText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  savingGoalQuickAddButtonTextGradient: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  // Investment Suggestions Page Styles
  investmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 12,
  },
  investmentBackButton: {
    padding: 4,
  },
  investmentHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  investmentTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  investmentSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  investmentInfoCard: {
    marginBottom: 20,
    borderRadius: 14,
    overflow: 'hidden',
  },
  investmentInfoCardGradient: {
    padding: 20,
  },
  investmentInfoCardContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  investmentInfoIcon: {
    marginRight: 12,
  },
  investmentInfoText: {
    flex: 1,
  },
  investmentInfoTitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 8,
  },
  investmentInfoDescription: {
    fontSize: 13,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  investmentFilterTabs: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
  },
  investmentFilterTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A2332',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  investmentFilterTabActive: {
    backgroundColor: '#51A2FF',
  },
  investmentFilterTabText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#99A1AF',
    fontWeight: '500',
  },
  investmentFilterTabTextActive: {
    fontSize: 13,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  investmentChannelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  investmentChannelIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  investmentChannelContent: {
    flex: 1,
  },
  investmentChannelName: {
    fontSize: 16,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  investmentChannelDescription: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginBottom: 8,
  },
  investmentChannelTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  investmentTag: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  investmentTagText: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '500',
  },
  investmentDisclaimer: {
    flexDirection: 'row',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    marginBottom: 20,
    gap: 12,
  },
  investmentDisclaimerText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  // Expense Analysis Styles
  expenseAnalysisHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 12,
  },
  expenseAnalysisBackButton: {
    padding: 4,
  },
  expenseAnalysisHeaderCenter: {
    flex: 1,
    alignItems: 'center',
    marginLeft: 8,
  },
  expenseAnalysisTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  expenseAnalysisSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  expenseAnalysisTabs: {
    flexDirection: 'row',
    gap: 4,
    marginLeft: 8,
  },
  expenseAnalysisTab: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: '#1A2332',
  },
  expenseAnalysisTabActive: {
    backgroundColor: '#9810FA',
  },
  expenseAnalysisTabText: {
    fontSize: 11,
    lineHeight: 16,
    color: '#99A1AF',
    fontWeight: '500',
  },
  expenseAnalysisTabTextActive: {
    color: '#FFFFFF',
  },
  expenseAnalysisTotalCard: {
    padding: 20,
    borderRadius: 14,
    minHeight: 140,
  },
  expenseAnalysisTotalCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  expenseAnalysisTotalCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  expenseAnalysisTotalCardLabel: {
    fontSize: 13.2,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  expenseAnalysisBadge: {
    backgroundColor: '#EF4444',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  expenseAnalysisBadgeText: {
    fontSize: 11,
    lineHeight: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  expenseAnalysisTotalAmount: {
    fontSize: 32,
    lineHeight: 40,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 8,
  },
  expenseAnalysisTotalSubtitle: {
    fontSize: 13,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  expenseAnalysisSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  expenseAnalysisSectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  expenseAnalysisSectionTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 16,
  },
  expenseAnalysisSmartButton: {
    backgroundColor: '#51A2FF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  expenseAnalysisSmartButtonText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  expenseAnalysisInsightCard: {
    flexDirection: 'row',
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  expenseAnalysisInsightIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  expenseAnalysisInsightContent: {
    flex: 1,
  },
  expenseAnalysisInsightTitle: {
    fontSize: 14.5,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  expenseAnalysisInsightDescription: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
    marginBottom: 8,
  },
  expenseAnalysisInsightTip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  expenseAnalysisInsightTipText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
  },
  expenseAnalysisPieChartContainer: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  expenseAnalysisPieChartPlaceholder: {
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseAnalysisPieChartCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#2A2A3E',
  },
  expenseAnalysisLegend: {
    flex: 1,
    marginLeft: 16,
  },
  expenseAnalysisLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  expenseAnalysisLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  expenseAnalysisLegendName: {
    flex: 1,
    fontSize: 12.9,
    lineHeight: 20,
    color: '#D1D5DC',
  },
  expenseAnalysisLegendPercentage: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
    marginRight: 8,
    minWidth: 40,
  },
  expenseAnalysisLegendAmount: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  expenseAnalysisLineChartContainer: {
    height: 150,
    marginBottom: 12,
  },
  expenseAnalysisLineChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '100%',
    paddingHorizontal: 8,
  },
  expenseAnalysisLineChartPoint: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  expenseAnalysisLineChartBar: {
    width: 8,
    backgroundColor: '#EF4444',
    borderRadius: 4,
    minHeight: 4,
  },
  expenseAnalysisLineChartLabel: {
    fontSize: 10,
    lineHeight: 16,
    color: '#99A1AF',
    marginTop: 4,
  },
  expenseAnalysisLineChartSubtitle: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
    textAlign: 'center',
  },
  expenseAnalysisComparisonItem: {
    marginBottom: 16,
  },
  expenseAnalysisComparisonCategory: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
    marginBottom: 8,
  },
  expenseAnalysisComparisonBars: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  expenseAnalysisComparisonBarContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  expenseAnalysisComparisonBar: {
    height: 24,
    borderRadius: 4,
    minWidth: 20,
  },
  expenseAnalysisComparisonValue: {
    fontSize: 11,
    lineHeight: 16,
    color: '#99A1AF',
  },
  expenseAnalysisComparisonChange: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    textAlign: 'right',
  },
  expenseAnalysisSavingTipCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  expenseAnalysisSavingTipIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FBBF24',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  expenseAnalysisSavingTipEmoji: {
    fontSize: 24,
  },
  expenseAnalysisSavingTipContent: {
    flex: 1,
  },
  expenseAnalysisSavingTipTitle: {
    fontSize: 14.5,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  expenseAnalysisSavingTipDescription: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  expenseAnalysisSavingTipButton: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  expenseAnalysisSavingTipButtonText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  expenseAnalysisUnusualTransactionsContainer: {
    gap: 12,
  },
  expenseAnalysisUnusualTransactionCard: {
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  expenseAnalysisUnusualTransactionContent: {
    flex: 1,
  },
  expenseAnalysisUnusualTransactionName: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  expenseAnalysisUnusualTransactionAmount: {
    fontSize: 16,
    lineHeight: 24,
    color: '#EF4444',
    fontWeight: '600',
    marginBottom: 4,
  },
  expenseAnalysisUnusualTransactionTime: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginBottom: 4,
  },
  expenseAnalysisUnusualTransactionDescription: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  // Financial Analysis Styles
  financialAnalysisHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingTop: 12,
  },
  financialAnalysisBackButton: {
    padding: 4,
  },
  financialAnalysisHeaderCenter: {
    flex: 1,
    alignItems: 'center',
    marginLeft: 8,
  },
  financialAnalysisTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  financialAnalysisSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  financialAnalysisSettingsButton: {
    padding: 4,
    marginLeft: 8,
  },
  financialAnalysisHealthScoreCard: {
    padding: 20,
    borderRadius: 14,
    minHeight: 200,
  },
  financialAnalysisHealthScoreHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  financialAnalysisHealthScoreTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  financialAnalysisHealthScoreTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  financialAnalysisRestoreButton: {
    backgroundColor: '#FBBF24',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  financialAnalysisRestoreButtonText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  financialAnalysisHealthScoreSubtitle: {
    fontSize: 12.9,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 20,
  },
  financialAnalysisHealthScoreContent: {
    flexDirection: 'row',
    gap: 20,
  },
  financialAnalysisHealthScoreCircleContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  financialAnalysisHealthScoreCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 8,
    borderColor: '#FBBF24',
  },
  financialAnalysisHealthScoreValue: {
    fontSize: 28,
    lineHeight: 36,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  financialAnalysisHealthScoreMax: {
    fontSize: 12,
    lineHeight: 18,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  financialAnalysisHealthScoreFactors: {
    flex: 1,
    gap: 12,
  },
  financialAnalysisHealthScoreFactor: {
    marginBottom: 8,
  },
  financialAnalysisHealthScoreFactorName: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  financialAnalysisHealthScoreBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  financialAnalysisHealthScoreBarTrack: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  financialAnalysisHealthScoreBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  financialAnalysisHealthScoreFactorValue: {
    fontSize: 11,
    lineHeight: 16,
    color: '#FFFFFF',
    minWidth: 40,
  },
  financialAnalysisSectionHeader: {
    marginBottom: 16,
  },
  financialAnalysisInsightTabs: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  financialAnalysisInsightTab: {
    flex: 1,
    backgroundColor: '#0F1729',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  financialAnalysisInsightTabActive: {
    backgroundColor: '#51A2FF',
  },
  financialAnalysisInsightTabText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    fontWeight: '500',
  },
  financialAnalysisInsightTabTextActive: {
    color: '#FFFFFF',
  },
  financialAnalysisInsightCard: {
    flexDirection: 'row',
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  financialAnalysisInsightIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  financialAnalysisInsightContent: {
    flex: 1,
  },
  financialAnalysisInsightTitle: {
    fontSize: 14.5,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  financialAnalysisInsightDescription: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  financialAnalysisMetricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  financialAnalysisMetricCard: {
    width: '48%',
    backgroundColor: '#1A2332',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  financialAnalysisMetricIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  financialAnalysisMetricValue: {
    fontSize: 20,
    lineHeight: 28,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
    textAlign: 'center',
  },
  financialAnalysisMetricLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginBottom: 4,
    textAlign: 'center',
  },
  financialAnalysisMetricChange: {
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 2,
  },
  financialAnalysisMetricSubtitle: {
    fontSize: 11,
    lineHeight: 16,
    color: '#99A1AF',
  },
  financialAnalysisGrowthChartContainer: {
    height: 180,
    marginBottom: 16,
  },
  financialAnalysisGrowthChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '100%',
    paddingHorizontal: 8,
  },
  financialAnalysisGrowthChartPoint: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  financialAnalysisGrowthChartBar: {
    width: 12,
    backgroundColor: '#10B981',
    borderRadius: 6,
    minHeight: 4,
  },
  financialAnalysisGrowthChartLabel: {
    fontSize: 10,
    lineHeight: 16,
    color: '#99A1AF',
    marginTop: 4,
  },
  financialAnalysisGrowthSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  financialAnalysisGrowthSummaryText: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#99A1AF',
  },
  financialAnalysisGrowthSummaryValue: {
    color: '#10B981',
    fontWeight: '600',
  },
  financialAnalysisGrowthSummaryAmount: {
    fontSize: 14.5,
    lineHeight: 22,
    fontWeight: '600',
  },
  financialAnalysisGoalProgressCard: {
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  financialAnalysisGoalProgressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  financialAnalysisGoalProgressName: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  financialAnalysisGoalProgressPercentage: {
    fontSize: 13.2,
    lineHeight: 20,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  financialAnalysisGoalProgressBarContainer: {
    marginBottom: 8,
  },
  financialAnalysisGoalProgressBarTrack: {
    height: 8,
    backgroundColor: '#0F1729',
    borderRadius: 4,
    overflow: 'hidden',
  },
  financialAnalysisGoalProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  financialAnalysisGoalProgressAmount: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
  },
  financialAnalysisRecommendationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#0F1729',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  financialAnalysisRecommendationIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  financialAnalysisRecommendationContent: {
    flex: 1,
  },
  financialAnalysisRecommendationTitle: {
    fontSize: 14.5,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 4,
  },
  financialAnalysisRecommendationDescription: {
    fontSize: 12.9,
    lineHeight: 20,
    color: '#99A1AF',
    marginBottom: 4,
  },
  financialAnalysisRecommendationAction: {
    fontSize: 12,
    lineHeight: 18,
    color: '#51A2FF',
    fontWeight: '500',
  },
  financialAnalysisRecommendationButton: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 8,
  },
  financialAnalysisRecommendationButtonText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  financialAnalysisPredictionCard: {
    padding: 20,
    borderRadius: 14,
    minHeight: 200,
  },
  financialAnalysisPredictionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  financialAnalysisPredictionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  financialAnalysisPredictionTitle: {
    fontSize: 15.1,
    lineHeight: 24,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  financialAnalysisPredictionBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  financialAnalysisPredictionBadgeText: {
    fontSize: 10,
    lineHeight: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  financialAnalysisPredictionItem: {
    marginBottom: 16,
  },
  financialAnalysisPredictionLabel: {
    fontSize: 12.9,
    lineHeight: 20,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 4,
  },
  financialAnalysisPredictionValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  financialAnalysisPredictionValue: {
    fontSize: 18,
    lineHeight: 26,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  financialAnalysisPredictionChange: {
    fontSize: 13,
    lineHeight: 20,
    color: '#10B981',
    fontWeight: '500',
  },
  financialAnalysisPredictionConfidence: {
    backgroundColor: 'rgba(81, 162, 255, 0.2)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  financialAnalysisPredictionConfidenceText: {
    fontSize: 10,
    lineHeight: 14,
    color: '#51A2FF',
    fontWeight: '500',
  },
  financialAnalysisPredictionDisclaimer: {
    fontSize: 10,
    lineHeight: 16,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 8,
    textAlign: 'center',
  },
  // Account Settings Page Styles
  accountSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingTop: 12,
  },
  accountSettingsBackButton: {
    padding: 4,
  },
  accountSettingsHeaderCenter: {
    flex: 1,
    alignItems: 'center',
  },
  accountSettingsTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  accountSettingsEditButton: {
    padding: 4,
  },
  accountSettingsProfileSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  accountSettingsProfileName: {
    fontSize: 20,
    lineHeight: 28,
    color: '#FFFFFF',
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 8,
  },
  accountSettingsMemberSince: {
    fontSize: 13,
    lineHeight: 20,
    color: '#99A1AF',
  },
  accountSettingsSection: {
    marginBottom: 24,
  },
  accountSettingsSectionTitle: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 16,
  },
  accountSettingsInfoContainer: {
    backgroundColor: '#1A2332',
    borderRadius: 14,
    overflow: 'hidden',
  },
  accountSettingsInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0F1729',
  },
  accountSettingsInfoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  accountSettingsInfoContent: {
    flex: 1,
  },
  accountSettingsInfoLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
    marginBottom: 4,
  },
  accountSettingsInfoValue: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  accountSettingsStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  accountSettingsStatCard: {
    width: '48%',
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 100,
  },
  accountSettingsStatValue: {
    fontSize: 28,
    lineHeight: 36,
    color: '#FFFFFF',
    fontWeight: '600',
    marginBottom: 8,
  },
  accountSettingsStatLabel: {
    fontSize: 12,
    lineHeight: 18,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  accountSettingsDangerZone: {
    backgroundColor: '#1A2332',
    borderRadius: 14,
    overflow: 'hidden',
  },
  accountSettingsDangerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0F1729',
  },
  accountSettingsDangerContent: {
    flex: 1,
  },
  accountSettingsDangerLabel: {
    fontSize: 15,
    lineHeight: 22,
    color: '#FB2C36',
    fontWeight: '500',
    marginBottom: 4,
  },
  accountSettingsDangerDescription: {
    fontSize: 12,
    lineHeight: 18,
    color: '#99A1AF',
  },
  // Account tab: bottom sheet menu (reference; account.tsx uses local styles)
  accountBottomSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#6B7280',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  accountBottomSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    gap: 16,
  },
  accountBottomSheetItemText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  // Delete money source dialog (reference; DeleteMoneySourceDialog has its own styles)
  deleteDialogTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  deleteDialogMessage: {
    color: '#E5E7EB',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
  },
});
